import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { createHash } from 'node:crypto';
const root = path.dirname(fileURLToPath(import.meta.url));
const read = file => readFileSync(path.join(root, file), 'utf8');
const data = JSON.parse(read('public/data/catalog.json'));
const pages = JSON.parse(read('templates/pages.json'));
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const price = n => new Intl.NumberFormat('pt-BR', {style:'currency', currency:'BRL'}).format(n);
const nav = [['','Início'],['nossa-historia','Nossa História'],['enoteca','Enoteca'],['gastronomia','Gastronomia'],['experiencia','Experiência'],['contato','Contato']];
const facts = p => `<p class="demo-tag">Produto demonstrativo · informações ilustrativas</p><p>${esc(p.description)}</p><dl class="wine-facts">${Object.entries(data.fields).filter(([key])=>p.facts[key]).map(([key,label])=>`<div><dt>${esc(label)}</dt><dd>${esc(p.facts[key])}</dd></div>`).join('')}</dl>`;
function catalog(type, limit = -1, filters = true, uid = type) {
 const products = data.catalog.filter(p=>p.category===type).slice(0,limit<0?undefined:limit);
 return `<div class="catalog" id="catalog-${uid}"><p class="demo-tag">SELEÇÃO DEMONSTRATIVA · PREÇOS ILUSTRATIVOS</p>${filters?`<form class="filters" aria-label="Filtrar vinhos"><p>Combine classificações. Dentro de cada grupo, escolha uma opção.</p><div class="filter-fields">${Object.entries(data.classifications).map(([key,[label,terms]])=>`<label>${esc(label)}<select name="${key}"><option value="">Todos</option>${Object.entries(terms).map(([value,name])=>`<option value="${value}">${esc(name)}</option>`).join('')}</select></label>`).join('')}<button type="reset" class="reset-filters">Limpar filtros</button></div></form>`:''}<div class="carousel-toolbar"><p class="result-count" role="status" aria-live="polite">${products.length} produtos</p><div><button type="button" data-direction="-1" aria-label="Produtos anteriores" aria-controls="${uid}-track">←</button><button type="button" data-direction="1" aria-label="Próximos produtos" aria-controls="${uid}-track">→</button></div></div><div class="product-track" id="${uid}-track" tabindex="0" role="region" aria-label="Produtos: use as setas para percorrer">${products.map(p=>`<article class="product-card" data-terms="${esc(JSON.stringify(p.terms))}"><div class="product-image"><img src="${esc(p.image)}" alt="${esc(p.name)} — fotografia ilustrativa" loading="lazy"><div class="quick-info"><span>${esc(p.facts.uvas)}</span><span>Safra ${esc(p.facts.safra||'não se aplica')}</span><span>${esc(p.facts.harmonizacao)}</span></div></div><div class="product-copy"><p class="eyebrow">${esc(p.facts.regiao)}</p><h3><a class="product-detail" data-dialog="${uid}-${p.slug}" href="/produto/${p.slug}/">${esc(p.name)} <span aria-hidden="true">↗</span></a></h3><p>${esc(p.facts.produtor)}</p><div class="price">${price(p.price)}<span>demonstrativo</span></div></div></article>`).join('')}</div><p class="empty-results" hidden>Nenhum vinho combina com esses filtros. Experimente outra combinação.</p>${products.map(p=>`<dialog id="${uid}-${p.slug}" class="product-dialog" aria-labelledby="${uid}-${p.slug}-title"><button type="button" class="close-dialog" aria-label="Fechar detalhes">Fechar ×</button><h2 id="${uid}-${p.slug}-title">${esc(p.name)}</h2>${facts(p)}<button type="button" data-add="${p.slug}">Adicionar ao carrinho demonstrativo</button></dialog>`).join('')}</div>`;
}
function document(slug, title, description, body) {
 return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${esc(description)}"><meta name="robots" content="noindex,follow"><title>${esc(title)} – Raccolto Galvani</title><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"><link rel="stylesheet" href="/assets/portfolio.css"><script src="/assets/site.js" defer></script><script src="/assets/portfolio.js" defer></script></head><body><a class="skip" href="#conteudo">Pular para o conteúdo</a><div class="topline">ROMA, NEL CUORE · UMA HISTÓRIA IMAGINADA DESDE 1982</div><header class="site-header"><a class="brand" href="/"><span class="crest" aria-hidden="true">RG</span><span>Raccolto Galvani<small>CUCINA ITALIANA & ENOTECA</small></span></a><button class="menu-toggle" aria-controls="navigation" aria-expanded="false">Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Principal"><ul>${nav.map(([p,label])=>`<li><a href="/${p?p+'/':''}"${slug===p?' aria-current="page"':''}>${label}</a></li>`).join('')}</ul></nav><div class="utility"><a href="/conta/">Conta</a><a href="/carrinho/">Carrinho <span aria-hidden="true">↗</span></a></div></header><main id="conteudo">${body}</main><footer class="site-footer"><div><a class="brand" href="/">Raccolto Galvani</a><p>À mesa, o tempo encontra outro ritmo.</p><small>Roma · localização conceitual</small></div><div><p class="eyebrow">LA CASA</p><a href="/nossa-historia/">Nossa história</a><a href="/experiencia/">Experiência</a><a href="/contato/">Contato</a></div><div><p class="eyebrow">INFORMAÇÕES</p><a href="/termos/">Termos da demonstração</a><a href="/privacidade/">Privacidade</a><a href="/conta/">Minha conta</a></div><div class="footer-bottom"><span>© 2026 Raccolto Galvani · Projeto fictício de portfólio.</span><span>Produtos e experiência comercial demonstrativos. Nenhuma compra real.</span></div></footer><p id="site-status" class="sr-only" role="status" aria-live="polite"></p></body></html>`;
}
function emit(slug,title,description,body) {
 const dir = path.join(root,'public',slug); mkdirSync(dir,{recursive:true});
 writeFileSync(path.join(dir,'index.html'),document(slug,title,description,body));
}
const heading = (title,italian,description) => `<header class="page-heading"><p class="eyebrow">RACCOLTO GALVANI / ${esc(italian)}</p><h1>${esc(title)}</h1><p>${esc(description)}</p></header>`;
emit('', 'Início','Raccolto Galvani: um portfólio fictício de cozinha italiana, vinhos e encontros à mesa.',read('templates/home.html').replace('{{HOME_CATALOG}}',catalog('vinho',6,false,'home')));
for (const [slug,p] of Object.entries(pages)) {
 let content=p.content.replace('[rg_catalog type="vinho"]',catalog('vinho')).replace('[rg_catalog type="especialidade" filters="no"]',catalog('especialidade',-1,false));
 if(slug==='contato') content=content.replace('Para questões técnicas ou remoção de dados de teste, procure o administrador que disponibilizou este ambiente. Não há formulário de contato nem envio de e-mails neste site.','Esta versão estática não possui formulário de contato nem envio de e-mails. Para apagar a seleção local, use “Limpar seleção” no carrinho ou limpe os dados deste site no navegador.');
 emit(slug,p.title,p.description,heading(p.title,p.italian,p.description)+`<article class="page-content section">${content}</article>`);
}
const special = {
 conta:['Conta','IL TUO SPAZIO','Uma apresentação do espaço do cliente, sem cadastro ou autenticação.',`<div class="prose"><p class="demo-notice">Conta/login demonstrativos. Não há autenticação, cadastro, senha ou coleta de dados pessoais nesta versão.</p><h2>Seu espaço à mesa.</h2><p>Explore como seria acompanhar uma seleção. Nenhum usuário será criado e nenhum acesso será autenticado.</p><button type="button" id="account-preview" aria-expanded="false" aria-controls="account-panel">Explorar espaço demonstrativo</button><section id="account-panel" hidden><h3>Prévia da conta · demonstração</h3><p>Este painel é somente uma apresentação. Você pode explorar a enoteca e revisar a seleção armazenada no seu navegador.</p><a class="button" href="/carrinho/">Ver seleção demonstrativa</a><p>Não existem pedidos, histórico de compras ou dados de perfil.</p></section></div>`],
 carrinho:['Carrinho','LA TUA SELEZIONE','Seleção local e simulação de retirada ou entrega, sem compras reais.',`<p class="demo-notice">Demonstração de portfólio: valores ilustrativos. Nenhuma compra real, cobrança ou pedido será realizado.</p><p id="storage-notice" hidden>O armazenamento local está indisponível. A seleção funciona somente nesta página enquanto ela estiver aberta.</p><div id="cart-content" aria-live="polite"></div><noscript><p>Ative JavaScript para usar o carrinho local. Nenhuma informação será enviada.</p></noscript><aside class="demo-panel"><h2>Uma experiência demonstrativa</h2><p>A simulação salva somente sua preferência neste navegador. Não solicitamos endereço.</p><form id="fulfilment-form"><fieldset><legend>Como você imaginaria receber?</legend><label><input type="radio" name="fulfilment" value="retirada" checked> Retirada demonstrativa</label><label><input type="radio" name="fulfilment" value="entrega"> Entrega demonstrativa (sem endereço)</label></fieldset><button type="submit">Simular escolha</button></form><p id="cart-status" role="status" aria-live="polite"></p><button id="clear-cart" type="button">Limpar seleção</button></aside>`],
 termos:['Termos','LE CONDIZIONI','Condições de uso da versão estática do portfólio fictício.',`<div class="prose"><h2>Uma demonstração, do início ao fim</h2><p>Raccolto Galvani é um projeto fictício. Mônaco, 1982, o chef Luis Galvani e Roma fazem parte da narrativa criativa. Não há restaurante real, endereço, certificações ou depoimentos de clientes.</p><h3>Catálogo e valores</h3><p>Nomes, produtores, safras, fichas e preços em reais são ilustrativos. Fotografias licenciadas são referências visuais e não representam produtos à venda. Não existe oferta comercial.</p><h3>Conta e seleção</h3><p>O espaço da conta é uma prévia visual, sem autenticação ou cadastro. Não digite dados pessoais: não há campos de senha, e-mail ou endereço. O carrinho guarda somente identificadores de produtos, quantidades e preferência de retirada/entrega no navegador. Não há pedidos, reservas, pagamentos ou e-mails.</p><h3>Disponibilidade e imagens</h3><p>A demonstração pode ser interrompida. As fotografias locais usam a licença Unsplash, com fontes no repositório. Este texto descreve o projeto e não inventa uma empresa nem afirma conformidade jurídica.</p></div>`],
 privacidade:['Política de Privacidade','LA PRIVACY','Armazenamento local da seleção, sem contas ou rastreadores opcionais.',`<div class="prose"><h2>Privacidade nesta versão estática</h2><p>Este é um portfólio fictício. Não há banco de dados de visitantes, cadastro, autenticação, formulário de contato, senha ou coleta de endereço nesta aplicação.</p><h3>Seleção no navegador</h3><p>O localStorage usa a chave <code>rg-portfolio-cart-v1</code> para guardar apenas identificadores públicos de produtos, quantidades e preferência demonstrativa entre retirada e entrega. Esses dados não são enviados a um servidor e permanecem até você limpar a seleção ou os dados do site no navegador. Caso o armazenamento seja bloqueado, o carrinho funciona apenas em memória na página atual.</p><h3>Cookies e serviços</h3><p>A aplicação não cria cookies, analytics ou pixels, nem carrega fotos ou fontes de terceiros. Não há banner de consentimento opcional. O provedor de hospedagem Vercel pode processar registros técnicos da requisição, como IP, caminho e agente do navegador, para servir e proteger o site; esta aplicação não controla a retenção desses registros. Não afirmamos ausência de registros da hospedagem.</p><h3>Remoção</h3><p>Use “Limpar seleção” no carrinho para apagar o armazenamento da aplicação. Não há contas ou dados de perfil para exportar. A versão é independente do laboratório WordPress e não compartilha sua sessão ou seu banco. Este texto descreve o comportamento, sem declaração de conformidade jurídica.</p></div>`]
};
for (const [slug,[title,it,desc,body]] of Object.entries(special)) emit(slug,title,desc,heading(title,it,desc)+`<article class="page-content section">${body}</article>`);
for(const p of data.catalog) emit(`produto/${p.slug}`,p.name,'Ficha demonstrativa e fotografia ilustrativa. Sem compras reais.',heading(p.name,'LA SELEZIONE','Produto demonstrativo · preço ilustrativo')+`<article class="section"><div class="split"><img class="detail-photo" src="${esc(p.image)}" alt="${esc(p.name)} — fotografia ilustrativa"><div>${facts(p)}<p class="price">${price(p.price)} · demonstrativo</p><button type="button" data-add="${p.slug}">Adicionar ao carrinho demonstrativo</button><p><a href="/${p.category==='vinho'?'enoteca':'gastronomia'}/">Voltar à seleção</a></p></div></div></article>`);
writeFileSync(path.join(root,'public/404.html'),document('404','Página não encontrada','Esta página não faz parte da demonstração.',heading('Página não encontrada','LA CASA','Continue explorando nossa casa imaginada.')+'<div class="section"><a class="button" href="/">Voltar ao início</a></div>'));
writeFileSync(path.join(root,'public/data/build.json'), JSON.stringify({
  version: 'raccolto-static-v1',
  commit: process.env.VERCEL_GIT_COMMIT_SHA || null,
  catalogSha256: createHash('sha256').update(read('public/data/catalog.json')).digest('hex')
}, null, 2) + '\n');
console.log(`Built ${1+Object.keys(pages).length+Object.keys(special).length+data.catalog.length} static pages + 404; ${data.catalog.length} public products. No WordPress connection.`);
