/* Requires playwright-core; RG_PLAYWRIGHT_PATH may point to its local installation. */
const { chromium } = require(process.env.RG_PLAYWRIGHT_PATH || 'playwright-core');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const { execFileSync } = require('node:child_process');
const base = (process.env.RG_SITE_URL || execFileSync('php', ['/tmp/rg-wp.phar', '--allow-root', '--path=/var/www/html', 'option', 'get', 'home'], { encoding: 'utf8' }).trim()).replace(/\/$/, '');
(async () => {
  const browser = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox','--no-proxy-server',`--host-resolver-rules=MAP ${new URL(base).hostname} 127.0.0.1`] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  const errors = [];
  const broken = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', r => { if (r.status() >= 400 && r.url().startsWith(base)) broken.push(`${r.status()} ${new URL(r.url()).pathname}`); });
  const goto = async path => { const r = await page.goto(base + path, { waitUntil: 'networkidle' }); assert.equal(r.status(),200,path); };
  const overflow = async () => assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'Horizontal page overflow');
  const images = async () => {
    await page.locator('img').evaluateAll(async elements => {
      await Promise.all(elements.map(img => { img.loading = 'eager'; return img.decode().catch(() => {}); }));
    });
    assert.deepEqual(await page.locator('img').evaluateAll(elements => elements.filter(img => !img.complete || img.naturalWidth === 0).map(img => img.getAttribute('src'))), [], 'Images must decode');
  };
  await goto('/');
  assert.equal(await page.locator('h1').count(),1);
  assert(!(await context.cookies()).some(c=>c.name.startsWith('sbjs_')), 'No optional attribution cookies');
  assert(await page.locator('footer').innerText().then(t=>t.includes('Projeto fictício')));
  await overflow();
  await page.evaluate(async () => { for(let y=0;y<document.body.scrollHeight;y+=650){window.scrollTo(0,y);await new Promise(r=>setTimeout(r,120));} window.scrollTo(0,0); });
  await page.waitForTimeout(800);
  await images();
  await page.screenshot({ path: '/tmp/rg-home-desktop.png', fullPage: true });
  for (const path of ['/nossa-historia/','/gastronomia/','/experiencia/','/contato/','/termos/','/privacidade/','/conta/','/carrinho/']) {
    await goto(path); await overflow(); await images();
    assert.equal(await page.locator('meta[name=description]').count(),1,path);
  }
  await goto('/enoteca/');
  await images();
  assert.equal(await page.locator('.product-card:visible').count(),9);
  const productPath = new URL(await page.locator('.product-detail').first().getAttribute('href')).pathname;
  await page.selectOption('select[name=cultivo]','organico');
  assert.equal(await page.locator('.product-card:visible').count(),4);
  await page.selectOption('select[name=cor]','laranja');
  assert.equal(await page.locator('.product-card:visible').count(),1);
  await page.selectOption('select[name=cultivo]','natural');
  assert.equal(await page.locator('.product-card:visible').count(),1);
  await page.selectOption('select[name=efervescencia]','espumante');
  assert.equal(await page.locator('.product-card:visible').count(),0);
  assert(await page.locator('.empty-results').isVisible());
  await page.click('.reset-filters');
  await page.waitForFunction(()=>[...document.querySelectorAll('.product-card')].filter(el=>!el.hidden).length===9);
  assert.equal(await page.locator('.product-card:visible').count(),9);
  const track = page.locator('.product-track');
  await track.focus(); await page.keyboard.press('ArrowRight'); await page.waitForTimeout(500);
  assert(await track.evaluate(el=>el.scrollLeft)>0,'Keyboard carousel');
  const previousScroll = await track.evaluate(el=>el.scrollLeft);
  await page.click('[data-direction="-1"]'); await page.waitForTimeout(700);
  assert(await track.evaluate(el=>el.scrollLeft) < previousScroll, 'Previous button moves carousel left');
  const detail = page.locator('.product-detail').first();
  await detail.focus(); await page.waitForTimeout(350);
  assert.equal(await page.locator('.product-card').first().locator('.quick-info').evaluate(el=>getComputedStyle(el).transform), 'matrix(1, 0, 0, 1, 0, 0)');
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('dialog[open]').count(),1);
  assert((await page.locator('dialog[open]').textContent()).includes('Ano de engarrafamento'));
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('dialog[open]').count(),0);
  assert(await detail.evaluate(el=>document.activeElement===el),'Dialog restores focus');
  await detail.click();
  await Promise.all([page.waitForURL('**/carrinho/'),page.locator('dialog[open] button[type=submit]').click()]);
  assert.equal(await page.locator('.cart_item').count(),1);
  assert.equal(await page.locator('.checkout-button').count(),0);
  await page.check('input[value=entrega]');
  await Promise.all([page.waitForNavigation({ waitUntil:'networkidle' }),page.getByRole('button',{name:'Simular escolha'}).click()]);
  assert((await page.locator('.woocommerce-message').innerText()).includes('Nenhum pedido'));
  assert(await page.locator('input[value=entrega]').isChecked());
  await page.check('input[value=retirada]');
  await Promise.all([page.waitForNavigation({ waitUntil:'networkidle' }),page.getByRole('button',{name:'Simular escolha'}).click()]);
  assert(await page.locator('input[value=retirada]').isChecked());
  await page.locator('input.qty').fill('2');
  await page.getByRole('button',{name:'Atualizar carrinho'}).click();
  await page.waitForTimeout(1500);
  assert.equal(await page.locator('input.qty').inputValue(),'2');
  await page.locator('.product-remove a').click();
  await page.waitForTimeout(1000);
  assert.equal(await page.locator('.cart_item').count(),0);
  await goto('/checkout/'); assert(new URL(page.url()).pathname==='/carrinho/','Checkout redirects');
  const response = await context.request.post('http://127.0.0.1/wp-json/wc/store/v1/checkout', {data:{}, headers:{Host:new URL(base).host}});
  assert.equal(response.status(),403);
  await goto(productPath); await images();
  assert((await page.locator('.wine-facts').first().textContent()).includes('Ano de engarrafamento'), 'Native product details');
  // The expected blocked response is not a broken site resource.
  await goto('/conta/');
  assert((await page.locator('.woocommerce-privacy-policy-text').textContent()).includes('Use somente dados de teste'), 'Registration privacy notice');
  const visibility = page.locator('form.register .show-password-input');
  assert.equal(await visibility.evaluate(el => getComputedStyle(el, '::before').content), '"Mostrar senha"');
  await visibility.click();
  assert.equal(await page.locator('#reg_password').getAttribute('type'), 'text');
  await visibility.click();
  assert.equal(await page.locator('#reg_password').getAttribute('type'), 'password');
  const email = `rg-qa-${Date.now()}@example.invalid`;
  const password = crypto.randomBytes(24).toString('base64url') + '!Aa9';
  fs.writeFileSync('/tmp/rg-qa-user.json',JSON.stringify({email}),{mode:0o600});
  await page.fill('#reg_email',email); await page.fill('#reg_password',password);
  await page.locator('#reg_password').press('Tab');
  await page.waitForFunction(() => document.querySelector('.woocommerce-password-strength')?.classList.contains('strong') && !document.querySelector('button[name=register]')?.disabled);
  try { await Promise.all([page.waitForNavigation({ waitUntil:'networkidle' }),page.getByRole('button',{name:'Cadastre-se',exact:true}).click()]); } catch(e) { console.log('Registration diagnostics:', await page.evaluate(()=>({errors:[...document.querySelectorAll('.woocommerce-error')].map(el=>el.textContent),invalidFields:[...document.querySelectorAll('form.register input')].filter(el=>!el.validity.valid).map(el=>el.id),buttonDisabled:document.querySelector('button[name=register]')?.disabled,strength:document.querySelector('.woocommerce-password-strength')?.textContent}))); await page.screenshot({path:'/tmp/rg-register-diagnostic.png',fullPage:true}); throw e; }
  assert(await page.locator('.woocommerce-MyAccount-navigation').isVisible(),'Registration and account');
  await page.locator('.woocommerce-MyAccount-navigation').getByRole('link',{name:'Sair',exact:true}).click();
  await page.waitForLoadState('networkidle');
  await page.fill('#username',email); await page.fill('#password',password);
  await Promise.all([page.waitForNavigation({waitUntil:'networkidle'}),page.getByRole('button',{name:'Acessar',exact:true}).click()]);
  assert(await page.locator('.woocommerce-MyAccount-navigation').isVisible(),'Login');
  const mobile = await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
  const phone = await mobile.newPage();
  await phone.goto(base+'/',{waitUntil:'networkidle'});
  assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile homepage overflow');
  await phone.getByRole('button',{name:/Menu/}).click();
  assert.equal(await phone.locator('.menu-toggle').getAttribute('aria-expanded'),'true');
  await phone.getByRole('navigation',{name:'Principal'}).getByRole('link',{name:'Enoteca',exact:true}).click();
  await phone.waitForLoadState('networkidle');
  assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile catalog overflow');
  await phone.locator('.product-detail').first().tap();
  assert.equal(await phone.locator('dialog[open]').count(),1);
  await phone.locator('dialog[open] .close-dialog').tap();
  await phone.screenshot({path:'/tmp/rg-enoteca-mobile.png',fullPage:true});
  assert.equal(await phone.locator('.motion-ready').count(),0,'Reduced motion');
  assert.deepEqual(errors,[],'JavaScript errors');
  assert.deepEqual(broken,[],'Broken resources');
  console.log('PASS: pages, metadata, images, desktop/mobile overflow, filters, carousel controls/keyboard, focus/Enter/Escape dialog, cart add/update/remove, pickup/delivery, checkout block, registration/login, reduced motion and JavaScript errors.');
  await browser.close();
})().catch(error => { console.error(error.name + ': ' + error.message.split('\n')[0]); if(error.stack) console.error(error.stack.split('\n').filter(line=>line.includes('browser-test.cjs')).join('\n')); process.exit(1); });
