<?php
// Run with: wp eval-file scripts/configure.php. Not a web endpoint.
if (!defined('WP_CLI') || !WP_CLI || !function_exists('wc_get_product')) { exit('Use WP-CLI com WooCommerce ativo.'); }
$pages = [
'inicio'=>['Início','IL BENVENUTO','A cozinha italiana, os vinhos e os encontros do portfólio fictício Raccolto Galvani.',''],
'nossa-historia'=>['Nossa História','LA NOSTRA STORIA','Uma narrativa fictícia: Mônaco, 1982, o chef Luis Galvani e uma casa italiana imaginada em Roma.', '<div class="split"><div><p class="eyebrow">MÔNACO · 1982</p><h2>Uma casa feita de memórias.</h2><p>Na história fictícia de Raccolto Galvani, o chef Luis Galvani funda a casa em Mônaco, em 1982. Sua inspiração está nos gestos cotidianos: abrir uma garrafa, preparar uma massa, oferecer mais um lugar à mesa.</p><p>A narrativa chega a uma localização conceitual em Roma. A cidade inspira uma cozinha generosa, atenta à estação e às pequenas diferenças entre cada território italiano.</p></div><img src="{{massa}}" alt="Massa italiana, referência visual da cozinha" loading="lazy" style="width:100%;height:420px;object-fit:cover"></div><div class="prose"><p class="editorial-quote">“Uma boa mesa começa com vontade de compartilhar.”</p><p>Frase autoral deste portfólio; não é um depoimento real.</p><h3>A tradição como ponto de partida</h3><p>A identidade da casa une o vinho, a gastronomia e o convívio. O catálogo permite explorar uvas, métodos e harmonizações sem apresentar as fichas demonstrativas como produtos comerciais reais.</p><p>Raccolto Galvani é um projeto fictício. Não há restaurante, endereço ou chef real representado por esta narrativa.</p></div>'],
'enoteca'=>['Enoteca','IL VINO, IL TERRITORIO','Explore vinhos demonstrativos por cor, açúcar, efervescência, especiais e cultivo, com fichas completas e harmonizações.','<p>Uma coleção imaginada de territórios e estilos. Combine os filtros e selecione um vinho para abrir a ficha completa. As fotografias são ilustrativas e não representam garrafas à venda.</p>[rg_catalog type="vinho"]'],
'gastronomia'=>['Gastronomia','SAPORI DELLA CASA','Frios, queijos e especialidades italianas demonstrativas para descobrir combinações à mesa.','<div class="split"><div><h2>Sabores para compartilhar.</h2><p>Um início de refeição pode ser um convite: o sabor delicado de um queijo, o contraste de um frio curado, uma massa que acolhe o molho.</p><p>Explore nossa seleção fictícia. As fichas incluem notas e sugestões de harmonização; preços e produtos são demonstrativos.</p></div><img src="{{mesa}}" alt="Pratos e ambiente de refeição italiana" loading="lazy" style="width:100%;height:380px;object-fit:cover"></div>[rg_catalog type="especialidade" filters="no"]'],
'experiencia'=>['Experiência','L’ARTE DEL CONVIVIO','Um roteiro conceitual de gastronomia, vinhos e convívio, sem reservas ou serviços reais.','<div class="split"><img src="{{ambiente}}" alt="Ambiente de restaurante usado como referência conceitual" loading="lazy" style="width:100%;height:450px;object-fit:cover"><div><p class="eyebrow">UNA SERATA IMMAGINATA</p><h2>O prazer de ficar.</h2><p>Uma mesa acolhedora, luz quente e tempo para descobrir novos sabores. Esta é a experiência que inspira o projeto.</p><p>Comece pelos queijos e frios, encontre um vinho que dialogue com o prato e deixe a conversa conduzir o restante.</p></div></div><div class="prose"><h3>Três tempos à mesa</h3><ol><li><strong>O encontro:</strong> uma seleção de antipasti e um vinho fresco.</li><li><strong>A descoberta:</strong> massas e sabores italianos com harmonizações sugeridas.</li><li><strong>A pausa:</strong> queijos maturados e uma última conversa.</li></ol><p>Não recebemos reservas, pedidos ou pagamentos. Tudo aqui é uma experiência de portfólio.</p><a class="button" href="{{enoteca}}">Monte sua seleção demonstrativa ↗</a></div>'],
'contato'=>['Contato','PARLIAMONE','Informações sobre o projeto fictício Raccolto Galvani e a demonstração do site.','<div class="prose"><h2>Sobre este encontro.</h2><p>Raccolto Galvani é um portfólio fictício de restaurante. Roma é uma localização conceitual; não há endereço físico, telefone comercial ou serviço de reservas.</p><h3>Quer explorar a casa?</h3><p>Visite a enoteca, descubra as especialidades e experimente o carrinho demonstrativo. Nenhuma compra real será realizada.</p><a class="button" href="{{enoteca}}">Explorar a enoteca ↗</a><h3>Suporte do laboratório</h3><p>Para questões técnicas ou remoção de dados de teste, procure o administrador que disponibilizou este ambiente. Não há formulário de contato nem envio de e-mails neste site.</p></div>'],
'conta'=>['Conta','IL TUO SPAZIO','Cadastro e acesso via WooCommerce e WordPress, em ambiente de demonstração sem e-mails.','[woocommerce_my_account]'],
'carrinho'=>['Carrinho','LA TUA SELEZIONE','Carrinho demonstrativo com escolha entre retirada e entrega. Sem pedidos, pagamentos ou compras reais.','<p class="demo-notice">Demonstração de portfólio: valores ilustrativos. Nenhuma compra real, cobrança ou pedido será realizado.</p>[woocommerce_cart]'],
'checkout'=>['Demonstração','SOLO UNA DEMO','Finalização comercial desabilitada. Nenhuma compra real será realizada.','<p>Este projeto não recebe pedidos ou pagamentos. Use o carrinho demonstrativo.</p>'],
'privacidade'=>['Política de Privacidade','LA PRIVACY','Dados de contas e sessão, cookies essenciais e ausência de rastreadores e e-mails na demonstração.','<div class="prose"><h2>Privacidade nesta demonstração</h2><p>Este texto descreve o funcionamento do laboratório Raccolto Galvani, um projeto fictício de portfólio. Não representa uma empresa nem uma declaração de conformidade jurídica.</p><h3>Dados e finalidade</h3><p>Ao criar uma conta de teste, WordPress e WooCommerce armazenam nome de usuário, e-mail e hash de senha no banco local. Campos de perfil e endereços preenchidos voluntariamente também podem ser armazenados. Não use informações pessoais reais nem reutilize uma senha.</p><p>O carrinho usa uma sessão do WooCommerce para guardar produtos e a escolha demonstrativa entre retirada e entrega. Não solicitamos endereço nessa simulação e não criamos pedidos.</p><h3>Cookies essenciais</h3><p>WordPress usa cookies de autenticação e WooCommerce usa cookies e armazenamento de sessão para o carrinho (como wp_woocommerce_session_, woocommerce_cart_hash e woocommerce_items_in_cart). São recursos necessários aos fluxos solicitados. A autenticação persiste conforme a opção “lembrar-me”; a sessão do carrinho normalmente expira em cerca de dois dias, conforme o WooCommerce.</p><p>Não instalamos analytics, pixels publicitários, fontes remotas ou cookies opcionais. As fotos são servidas localmente. Por isso, esta versão não apresenta um banner de consentimento opcional. Se esses serviços forem incluídos, será necessário implementar aceitar, rejeitar e rever escolhas antes de carregá-los.</p><h3>E-mails, logs e acesso</h3><p>O plugin Raccolto Core bloqueia todos os e-mails de WordPress enquanto ativo, inclusive recuperação de senha. Logs padrão do servidor podem registrar IP, caminho, data e agente do navegador para operação do laboratório. Não enviamos dados a serviços de marketing. O administrador do ambiente pode acessar e remover dados de teste e exportações pelos recursos do WordPress.</p><h3>Retenção e remoção</h3><p>Contas e informações preenchidas permanecem no laboratório até remoção pelo administrador; não há exclusão automática. Solicite ao administrador que forneceu o acesso a exclusão ou exportação pelos recursos nativos em Ferramentas do WordPress. Backups privados podem conservar cópias até sua remoção pelo administrador. Não há canal público de atendimento ou responsável empresarial fictício.</p></div>'],
 'termos'=>['Termos','LE CONDIZIONI','Condições reais de uso do portfólio fictício: produtos ilustrativos, contas de teste e ausência de transações.','<div class="prose"><h2>Uma demonstração, do início ao fim</h2><p>Raccolto Galvani é um projeto fictício de portfólio. A história de Mônaco, 1982, o chef Luis Galvani e a localização em Roma compõem uma narrativa criativa. Não há restaurante real, endereço, certificações ou depoimentos de clientes.</p><h3>Catálogo e valores</h3><p>Nomes, produtores, safras e fichas dos produtos são demonstrativos. Fotos licenciadas são referências visuais e não representam rótulos reais à venda. Preços em reais são ilustrativos e não constituem oferta comercial.</p><h3>Conta e carrinho</h3><p>O cadastro e o login usam WordPress e WooCommerce. Use apenas dados de teste. É possível adicionar, alterar e retirar produtos do carrinho e simular retirada ou entrega, sem gerar pedido, cobrança, reserva ou serviço. Gateways e finalização de compra estão bloqueados.</p><h3>Limites do laboratório</h3><p>Não há envio de e-mails, inclusive mensagens de recuperação de senha. O administrador pode redefinir acessos pelos recursos do WordPress. Este ambiente de desenvolvimento pode ser interrompido; não possui garantia de disponibilidade.</p><h3>Fotografias</h3><p>As fotografias são usadas sob a licença Unsplash. O registro de arquivos, fontes e uso está no documento FONTES-IMAGENS.md do projeto.</p><p>Estes termos descrevem a demonstração e não afirmam conformidade jurídica nem inventam uma empresa responsável.</p></div>'],
];
$ids=[];
foreach ($pages as $slug=>$data) {
    $page=get_page_by_path($slug);
    $content=strtr($data[3], ['{{massa}}'=>esc_url(get_theme_file_uri('assets/massa.jpg')), '{{mesa}}'=>esc_url(get_theme_file_uri('assets/mesa.jpg')), '{{ambiente}}'=>esc_url(get_theme_file_uri('assets/ambiente.jpg')), '{{enoteca}}'=>esc_url(home_url('/enoteca/'))]);
    if (!$page) {
        $id=wp_insert_post(['post_title'=>$data[0],'post_name'=>$slug,'post_content'=>$content,'post_status'=>'publish','post_type'=>'page'],true);
        if (is_wp_error($id)) { WP_CLI::error($id->get_error_message()); }
        update_post_meta($id,'_rg_seed','1');
    } else { $id=$page->ID; } // Preserve existing content, including editor changes.
    update_post_meta($id,'_rg_italian',$data[1]); update_post_meta($id,'_rg_description',$data[2]); $ids[$slug]=$id;
}
update_option('show_on_front','page');update_option('page_on_front',$ids['inicio']);
update_option('woocommerce_myaccount_page_id',$ids['conta']);update_option('woocommerce_cart_page_id',$ids['carrinho']);update_option('woocommerce_checkout_page_id',$ids['checkout']);
update_option('woocommerce_terms_page_id',$ids['termos']);update_option('wp_page_for_privacy_policy',$ids['privacidade']);
update_option('woocommerce_enable_myaccount_registration','yes');update_option('woocommerce_registration_generate_password','no');update_option('woocommerce_registration_generate_username','yes');
update_option('woocommerce_currency','BRL');update_option('woocommerce_price_decimal_sep',',');update_option('woocommerce_price_thousand_sep','.');update_option('woocommerce_currency_pos','left_space');update_option('woocommerce_calc_taxes','no');update_option('woocommerce_enable_reviews','no');update_option('woocommerce_enable_coupons','no');
update_option('woocommerce_allow_tracking','no');update_option('woocommerce_feature_order_attribution_enabled','no');update_option('woocommerce_coming_soon','no');update_option('woocommerce_store_address','');update_option('woocommerce_store_address_2','');update_option('woocommerce_store_city','');update_option('woocommerce_store_postcode','');
update_option('blogname','Raccolto Galvani');update_option('blogdescription','Cucina italiana & enoteca — projeto fictício');update_option('blog_public','0');update_option('permalink_structure','/%postname%/');
$menu=wp_get_nav_menu_object('Raccolto — Principal');$menu_id=$menu?$menu->term_id:wp_create_nav_menu('Raccolto — Principal');
$existing=wp_get_nav_menu_items($menu_id)?:[];
foreach (['inicio','nossa-historia','enoteca','gastronomia','experiencia','contato'] as $slug) {
    if (!array_filter($existing,fn($item)=>(int)$item->object_id===$ids[$slug])) { wp_update_nav_menu_item($menu_id,0,['menu-item-title'=>$pages[$slug][0],'menu-item-object'=>'page','menu-item-object-id'=>$ids[$slug],'menu-item-type'=>'post_type','menu-item-status'=>'publish']); }
}
$locations=get_theme_mod('nav_menu_locations',[]);$locations['primary']=$menu_id;set_theme_mod('nav_menu_locations',$locations);
foreach (rg_classifications() as $key=>$data) { foreach ($data[1] as $slug=>$label) { if (!term_exists($slug,'rg_'.$key)) { wp_insert_term($label,'rg_'.$key,['slug'=>$slug]); } } }
foreach (['vinho'=>'Vinhos demonstrativos','especialidade'=>'Especialidades demonstrativas'] as $slug=>$label) { if (!term_exists($slug,'product_cat')) { wp_insert_term($label,'product_cat',['slug'=>$slug]); } }
require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';
$images=[];
foreach (['vinho','massa','mesa'] as $name) {
    $found=get_posts(['post_type'=>'attachment','post_status'=>'inherit','meta_key'=>'_rg_image','meta_value'=>$name,'numberposts'=>1,'fields'=>'ids']);
    if ($found) { $images[$name]=$found[0]; continue; }
    $source=$name==='vinho'?WP_PLUGIN_DIR.'/raccolto-core/assets/vinho.jpg':get_theme_file_path('assets/'.$name.'.jpg');
    $tmp=wp_tempnam($name.'.jpg');copy($source,$tmp);
    $image=media_handle_sideload(['name'=>'raccolto-'.$name.'.jpg','tmp_name'=>$tmp],0,'Fotografia ilustrativa — fonte Unsplash, ver FONTES-IMAGENS.md');
    if (is_wp_error($image)) { WP_CLI::error($image->get_error_message()); }
    update_post_meta($image,'_rg_image',$name);update_post_meta($image,'_wp_attachment_image_alt','Fotografia ilustrativa de '.$name);$images[$name]=$image;
}
// All labels and producers below are invented; taxonomy combinations are for demonstration.
$wines=[
['rosso-casa','Rosso della Casa','Toscana, Itália','Sangiovese','2021','2023','148', ['cor'=>['tinto'],'acucar'=>['seco'],'efervescencia'=>['tranquilo'],'cultivo'=>['convencional']], 'Cereja, ervas e especiarias suaves.','Queijos maturados e ragù.'],
['bianco-luce','Bianco di Luce','Vêneto, Itália','Garganega','2023','2024','126',['cor'=>['branco'],'acucar'=>['seco'],'efervescencia'=>['tranquilo'],'cultivo'=>['organico']], 'Cítricos, pera e flores brancas.','Queijos frescos e massas leves.'],
['rosa-sera','Rosa della Sera','Puglia, Itália','Negroamaro','2023','2024','132',['cor'=>['rose'],'acucar'=>['demi-sec'],'efervescencia'=>['frisante'],'cultivo'=>['convencional']], 'Morango e frutas delicadas.','Antipasti e saladas.'],
['ambra-terra','Ambra di Terra','Friuli, Itália','Ribolla Gialla','2022','2023','179',['cor'=>['laranja'],'acucar'=>['seco'],'efervescencia'=>['tranquilo'],'cultivo'=>['organico','biodinamico','natural']], 'Casca de laranja, chá e frutas secas.','Frios curados e cogumelos.'],
['bollicine-festa','Bollicine di Festa','Lombardia, Itália','Chardonnay, Pinot Nero','2021','2024','198',['cor'=>['branco'],'acucar'=>['seco'],'efervescencia'=>['espumante'],'cultivo'=>['organico']], 'Maçã, brioche e final fresco.','Queijos suaves e antipasti.'],
['rosso-dolce','Rosso Dolce','Emilia-Romagna, Itália','Lambrusco','2023','2024','119',['cor'=>['tinto'],'acucar'=>['doce'],'efervescencia'=>['frisante'],'cultivo'=>['convencional']], 'Frutas vermelhas e doçura leve.','Frios e queijos semiduros.'],
['riserva-dopocena','Riserva Dopocena','Sicília, Itália','Grillo','2020','2024','219',['cor'=>['branco'],'acucar'=>['doce'],'efervescencia'=>['tranquilo'],'especiais'=>['fortificado'],'cultivo'=>['convencional']], 'Nozes, caramelo e frutas secas.','Queijos azuis e sobremesas.'],
['oro-autunno','Oro d’Autunno','Piemonte, Itália','Moscato','2022','2023','189',['cor'=>['branco'],'acucar'=>['doce'],'efervescencia'=>['tranquilo'],'especiais'=>['colheita-tardia','botritizado'],'cultivo'=>['organico']], 'Mel, damasco e flores.','Queijos azuis e tortas de fruta.'],
['ghiaccio-luce','Ghiaccio di Luce','Região alpina conceitual','Riesling','2022','2023','239',['cor'=>['branco'],'acucar'=>['doce'],'efervescencia'=>['tranquilo'],'especiais'=>['icewine'],'cultivo'=>['convencional']], 'Frutas de caroço e acidez intensa.','Queijos cremosos e sobremesas.'],
];
function rg_seed_product($key,$name,$price,$cat,$image,$fields,$terms=[]){
    $found=get_posts(['post_type'=>'product','post_status'=>'any','meta_key'=>'_rg_seed_key','meta_value'=>$key,'numberposts'=>1,'fields'=>'ids']);
    if ($found) { return; }
    $p=new WC_Product_Simple();$p->set_name($name.' · Demo');$p->set_slug($key);$p->set_status('publish');$p->set_regular_price($price);$p->set_virtual(true);$p->set_image_id($image);$p->set_reviews_allowed(false);$p->set_description('Produto demonstrativo do portfólio fictício Raccolto Galvani. Nome, produtor e ficha são ilustrativos; fotografia de referência. Não disponível para compra real.');$p->set_short_description('Seleção demonstrativa — nenhuma compra real será realizada.');
    $term=get_term_by('slug',$cat,'product_cat');$p->set_category_ids([$term->term_id]);$p->update_meta_data('_rg_seed_key',$key);
    foreach ($fields as $k=>$v) {$p->update_meta_data('_rg_'.$k,$v);} $id=$p->save();
    foreach ($terms as $k=>$values) {wp_set_object_terms($id,$values,'rg_'.$k);}
}
foreach ($wines as $w) {
    $cultivo=implode(', ',array_map(fn($v)=>rg_classifications()['cultivo'][1][$v],$w[7]['cultivo']));
    $fields=['regiao'=>$w[2],'produtor'=>'Tenuta Immaginaria (fictício)','uvas'=>$w[3],'safra'=>$w[4],'engarrafamento'=>$w[5],'colheita'=>in_array('icewine',$w[7]['especiais']??[],true)?'Manual, uvas congeladas (ilustrativo)':'Manual, seleção dos cachos (ilustrativo)','cultivo'=>$cultivo,'vinificacao'=>in_array('laranja',$w[7]['cor'],true)?'Fermentação com maceração das cascas (ilustrativo)':'Fermentação controlada e estágio selecionado (ilustrativo)','notas'=>$w[8],'harmonizacao'=>$w[9]];
    rg_seed_product($w[0],$w[1],$w[6],'vinho',$images['vinho'],$fields,$w[7]);
}
foreach ([['tagliere','Tagliere di Salumi','76','Seleção italiana conceitual','Frios curados, especiarias e textura delicada.','Rosso della Casa ou Lambrusco.','mesa'],['formaggi','Trio di Formaggi','68','Seleção italiana conceitual','Queijos de três maturações, do suave ao intenso.','Bianco di Luce ou Oro d’Autunno.','mesa'],['pasta','Pasta al Pomodoro','58','Cozinha italiana conceitual','Massa com molho de tomate e ervas frescas.','Rosso della Casa.','massa'],['burrata','Burrata e Orto','54','Cozinha italiana conceitual','Queijo fresco cremoso e vegetais de estação.','Bianco di Luce.','mesa']] as $food) {
    rg_seed_product($food[0],$food[1],$food[2],'especialidade',$images[$food[6]],['regiao'=>$food[3],'produtor'=>'Cucina Galvani (fictício)','notas'=>$food[4],'harmonizacao'=>$food[5]]);
}
flush_rewrite_rules();
WP_CLI::success('Páginas, menu, catálogo demonstrativo e opções configurados de forma idempotente. Conteúdo existente preservado.');
